# Generated by Django 2.0.2 on 2018-03-11 10:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
